from app import app  # <--- CRUCIAL: Import your Flask app
from extensions import db, celery, mail
from flask_mail import Message
from models.models import Application, PlacementDrive, StudentProfile, CompanyProfile, User
from datetime import datetime, timedelta
import csv
import os

# =================================================================
# a. Scheduled Job - Daily Reminders (Runs Daily)
# =================================================================
@celery.task()
def daily_deadline_reminder():
    with app.app_context(): # <--- ADDED APPLICATION CONTEXT
        # Find drives closing in exactly 2 days
        target_date = datetime.now().date() + timedelta(days=2)
        closing_drives = PlacementDrive.query.filter_by(application_deadline=target_date, status="Approved").all()
        
        if not closing_drives:
            return "No drives closing soon."

        students = StudentProfile.query.all()
        
        for drive in closing_drives:
            for student in students:
                # Check if student is eligible and HAS NOT applied yet
                has_applied = Application.query.filter_by(student_id=student.id, drive_id=drive.id).first()
                
                if not has_applied and float(student.cgpa) >= float(drive.min_cgpa):
                    user = User.query.get(student.user_id)
                    if user and user.email:
                        subject = f"Action Required: Deadline Approaching for {drive.job_title}"
                        body = f"Hello {student.full_name},\n\nThe application deadline for the '{drive.job_title}' drive is approaching on {target_date}. Since you meet the minimum CGPA criteria, we encourage you to apply before the link closes.\n\nRegards,\nPlacement Cell"
                        
                        try:
                            msg = Message(subject, recipients=[user.email])
                            msg.body = body
                            mail.send(msg)
                            print(f"[REMINDER SENT] -> {user.email}")
                        except Exception as e:
                            print(f"Failed to send reminder to {user.email}: {e}")

        return "Daily reminders process completed."

# ==========================================
# b. Monthly Activity Report 
# ==========================================
@celery.task()
def monthly_activity_report():
    with app.app_context(): # <--- ADDED APPLICATION CONTEXT
        # Gather statistics
        total_drives = PlacementDrive.query.count()
        total_applications = Application.query.count()
        total_selected = Application.query.filter_by(status="Selected").count()

        # Create HTML Template for Admin
        html_content = f"""
        <div style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
            <h2 style="color: #2c3e50;">Monthly Placement Activity Report</h2>
            <p>Here is the summary of the placement portal activities as of the 1st of this month:</p>
            <table border="1" cellpadding="10" cellspacing="0" style="border-collapse: collapse; width: 50%;">
                <tr style="background-color: #f8f9fa;">
                    <th style="text-align: left;">Metric</th>
                    <th style="text-align: left;">Count</th>
                </tr>
                <tr>
                    <td>Total Drives Conducted</td>
                    <td><strong>{total_drives}</strong></td>
                </tr>
                <tr>
                    <td>Total Applications Received</td>
                    <td><strong>{total_applications}</strong></td>
                </tr>
                <tr>
                    <td>Total Students Selected</td>
                    <td><strong>{total_selected}</strong></td>
                </tr>
            </table>
            <p style="margin-top: 20px; font-size: 0.9em; color: #7f8c8d;">Automated report generated by Placement Portal System.</p>
        </div>
        """
        
        # Send to Admin
        admin = User.query.filter_by(role='admin').first()
        if admin and admin.email:
            try:
                msg = Message("Monthly Placement Activity Report", recipients=[admin.email])
                msg.html = html_content
                mail.send(msg)
                print(f"[MONTHLY REPORT SENT] -> {admin.email}")
            except Exception as e:
                print(f"Failed to send monthly report: {e}")

        return "Monthly report generated and sent." 

# ==========================================
# c. User Triggered Async Job: Export CSV
# ==========================================
@celery.task()
def export_student_history_csv(student_id, student_email):
    with app.app_context(): # <--- ADDED APPLICATION CONTEXT
        # 1. Fetch data from DB
        apps = db.session.query(Application, PlacementDrive, CompanyProfile)\
            .join(PlacementDrive, Application.drive_id == PlacementDrive.id)\
            .join(CompanyProfile, PlacementDrive.company_id == CompanyProfile.id)\
            .filter(Application.student_id == student_id).all()

        # 2. Generate CSV File
        filename = f"export_{student_id}_{datetime.now().strftime('%Y%m%d%H%M%S')}.csv"
        filepath = os.path.join("static", "exports", filename)
        os.makedirs(os.path.dirname(filepath), exist_ok=True)

        with open(filepath, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(['Student ID', 'Company Name', 'Drive Title', 'Application Status'])
            
            # ---> FIX: Renamed 'app' to 'student_app' so it doesn't conflict with Flask's 'app'
            for student_app, drive, company in apps:
                writer.writerow([student_id, company.company_name, drive.job_title, student_app.status])

        # 3. Setup Email Data
        download_link = f"http://127.0.0.1:5000/{filepath}"
        subject = "Your Placement Portal CSV Export is Ready"
        body = f"Hello, your application history CSV has been generated. Download it here: {download_link}"

        # 4. Smart Domain Whitelisting Logic
        if student_email.strip().lower().endswith("iitm.ac.in"):
            try:
                msg = Message(subject, recipients=[student_email])
                msg.body = body
                mail.send(msg)
                print(f"[REAL EMAIL SENT] Successfully delivered to official ID: {student_email}")
            except Exception as e:
                print(f"[EMAIL FAILED] Could not send to {student_email}. Error: {str(e)}")
        else:
            print("--------------------------------------------------")
            print(f"[MOCK EMAIL - NON IITM DOMAIN] To: {student_email}")
            print(f"Subject: {subject}")
            print(f"Body: {body}")
            print("--------------------------------------------------")

        return filepath